[package]
name = "gwen2d_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.30.0"
egui-modal = "0.5.0"
egui_extras = "0.29.1"
log = "0.4"
env_logger = "0.11.5"
image = "0.24"
rfd = "0.12"